#!/usr/bin/env escript


main(Files)->
    {ok,Path} = file:get_cwd(),
    code:add_pathz(Path ++ "/ebin"),
    io:setopts([{encoding, unicode}]),
    io:format("~p~n", [Files]),
    lists:foreach(fun(Filename) ->
                          {ok, Records} = rezept:process_file(Filename, info),
                          lists:foreach(fun({ok, JSON}) ->
                                                io:format("~ts~n", [JSON]);
                                           ({error, E}) ->
                                                io:format("error: ~p~n", [E])
                                        end,
                                        lists:map(fun rezept:to_json/1, Records))
                  end, Files).
