%% generated by bin/ff1_matcher_generator.es at {{2015,5,18},{17,37,2}}
%% Source Filename: "/Users/kuenishi/Workbook1.csv"
%% data description: {<PayloadType>, [{<property name>, <required>, <datatype>}|{}]}
-define(DUMMY, {"DUMMY", [
    {}]}).
-define(A000010, {"A000010", [
    {birthymd, 1, 1, str},
    {sex, 2, 1, str},
    {postno, 3, 1, str},
    {}]}).
-define(A000020, {"A000020", [
    {nyuymd, 1, 1, str},
    {h_nyukb, 2, 1, str},
    {introkb, 3, 0, str},
    {o_nyukb, 4, 0, str},
    {e_nyukb, 5, 0, str},
    {emergkb, 6, 0, str},
    {zaitaku_befnyu, 7, 0, str},
    {}]}).
-define(A000030, {"A000030", [
    {taiymd, 1, 1, str},
    {h_taikb, 2, 1, str},
    {h_tenkkb, 3, 1, str},
    {death24kb, 4, 1, str},
    {zaitaku_afttai, 5, 0, str},
    {}]}).
-define(A000031, {"A000031", [
    {form1_staymd, 1, 1, str},
    {form1_endymd, 2, 1, str},
    {}]}).
-define(A000040, {"A000040", [
    {shinkacd, 2, 1, str},
    {tenkakb, 3, 1, str},
    {}]}).
-define(A000050, {"A000050", [
    {c_nyukb_ippan, 2, 1, str},
    {c_nyukb_seisin, 3, 1, str},
    {c_nyukb_other, 4, 1, str},
    {}]}).
-define(A000060, {"A000060", [
    {mainexam, 2, 1, str},
    {curekb, 3, 1, str},
    {}]}).
-define(A000070, {"A000070", [
    {b_taiymd, 1, 1, str},
    {b_nyukb, 2, 1, str},
    {}]}).
-define(A000080, {"A000080", [
    {reent_syu, 2, 2, str},
    {reent_reason_syu, 3, 2, str},
    {reent_reason, 9, 0, str},
    {}]}).
-define(A000090, {"A000090", [
    {retransfer_syu, 2, 2, str},
    {retransfer_reason_syu, 3, 2, str},
    {retransfer_reason, 9, 0, str},
    {}]}).
-define(A001010, {"A001010", [
    {height, 2, 1, str},
    {weight, 3, 1, str},
    {}]}).
-define(A001020, {"A001020", [
    {smk_index, 2, 1, numeric},
    {}]}).
-define(A001030, {"A001030", [
    {bedsore_nyu, 2, 1, str},
    {bedsore_tai, 3, 1, str},
    {}]}).
-define(A002010, {"A002010", [
    {pregkb, 2, 1, str},
    {pregweek_cnt, 3, 0, numeric},
    {}]}).
-define(A003010, {"A003010", [
    {b_weight, 2, 2, numeric},
    {birthweek, 3, 2, numeric},
    {}]}).
-define(A004010, {"A004010", [
    {fim_of_dep, 2, 2, str},
    {}]}).
-define(A006010, {"A006010", [
    {mainsick_cd, 2, 1, str},
    {mainsick_nm, 9, 1, str},
    {}]}).
-define(A006020, {"A006020", [
    {oppsick_cd, 2, 1, str},
    {oppsick_nm, 9, 1, str},
    {}]}).
-define(A006030, {"A006030", [
    {maxsick_cd, 2, 1, str},
    {disaddcd, 3, 0, str},
    {maxsick_nm, 9, 1, str},
    {}]}).
-define(A006031, {"A006031", [
    {nextsick_cd, 2, 2, str},
    {nextsick_nm, 9, 2, str},
    {}]}).
-define(A006040, {"A006040", [
    {heisick_cd, 2, 2, str},
    {heisick_nm, 9, 2, str},
    {}]}).
-define(A006050, {"A006050", [
    {hassick_cd, 2, 2, str},
    {hassick_nm, 9, 2, str},
    {}]}).
-define(A007010, {"A007010", [
    {ope_opeymd, 1, 2, str},
    {ope_tencd, 2, 2, str},
    {ope_cnt, 4, 2, str},
    {ope_side, 5, 2, str},
    {ope_ane, 6, 2, str},
    {ope_nm, 9, 2, str},
    {}]}).
-define(A008010, {"A008010", [
    {bringing_medicine, 2, 0, str},
    {}]}).
-define(ADL0010, {"ADL0010", [
    {n_adlkb, 2, 0, str},
    {}]}).
-define(ADL0020, {"ADL0020", [
    {t_adlkb, 2, 0, str},
    {}]}).
-define(CAN0010, {"CAN0010", [
    {cnc_no, 3, 2, str},
    {}]}).
-define(CAN0020, {"CAN0020", [
    {uicc_t, 3, 2, str},
    {uicc_n, 4, 2, str},
    {uicc_m, 5, 2, str},
    {uicc_edition, 6, 2, str},
    {}]}).
-define(CAN0030, {"CAN0030", [
    {cnc_stage, 3, 2, str},
    {}]}).
-define(CAN0040, {"CAN0040", [
    {chemokb, 3, 2, str},
    {}]}).
-define(JCS0010, {"JCS0010", [
    {n_jcskb, 2, 2, str},
    {}]}).
-define(JCS0020, {"JCS0020", [
    {t_jcskb, 2, 2, str},
    {}]}).
-define(M010010, {"M010010", [
    {n_mrs, 2, 2, str},
    {apoplexy_ymd, 3, 2, str},
    {}]}).
-define(M010020, {"M010020", [
    {t_mrs, 2, 2, str},
    {}]}).
-define(M010030, {"M010030", [
    {temodarkb, 2, 2, str},
    {}]}).
-define(M040010, {"M040010", [
    {hg_jn_case, 2, 2, str},
    {}]}).
-define(M040020, {"M040020", [
    {pneumonia_case, 2, 2, str},
    {}]}).
-define(M050010, {"M050010", [
    {nyha_case, 2, 2, str},
    {}]}).
-define(M050020, {"M050020", [
    {ccs_case, 2, 2, str},
    {}]}).
-define(M050030, {"M050030", [
    {killip_case, 2, 2, str},
    {}]}).
-define(M060010, {"M060010", [
    {child_case, 2, 2, str},
    {}]}).
-define(M060020, {"M060020", [
    {pancreas_case, 2, 2, str},
    {}]}).
-define(M070010, {"M070010", [
    {antirheumatic, 2, 2, str},
    {}]}).
-define(M120010, {"M120010", [
    {childbirthkb, 2, 2, str},
    {childbirth_bleed, 3, 0, str},
    {}]}).
-define(M160010, {"M160010", [
    {b_index, 2, 2, numeric},
    {}]}).
-define(M170010, {"M170010", [
    {n_gafmeasure, 2, 2, str},
    {}]}).
-define(M170020, {"M170020", [
    {seisin_nyuform, 2, 2, str},
    {isolation_days, 3, 2, numeric},
    {restraint_days, 4, 2, numeric},
    {}]}).
-define(Mzz0010, {"Mzz0010", [
    {injucd, 2, 2, str},
    {injunk, 9, 2, str},
    {}]}).
-define(DPCS_CODES, [
?A000010, ?A000020, ?A000030, ?A000031, ?A000040, ?A000050, ?A000060, ?A000070, ?A000080, ?A000090, ?A001010, ?A001020, ?A001030, ?A002010, ?A003010, ?A004010, ?A006010, ?A006020, ?A006030, ?A006031, ?A006040, ?A006050, ?A007010, ?A008010, ?ADL0010, ?ADL0020, ?CAN0010, ?CAN0020, ?CAN0030, ?CAN0040, ?JCS0010, ?JCS0020, ?M010010, ?M010020, ?M010030, ?M040010, ?M040020, ?M050010, ?M050020, ?M050030, ?M060010, ?M060020, ?M070010, ?M120010, ?M160010, ?M170010, ?M170020, ?Mzz0010, ?DUMMY]).
